global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "backend"
    static_configs:
      - targets: ["backend:8080"]
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
