FROM postgres:15

# Set environment variables
ENV POSTGRES_USER=user
ENV POSTGRES_PASSWORD=password
ENV POSTGRES_DB=dbname

# Copy custom pg_hba.conf
COPY ./config/pg_hba.conf /var/lib/postgresql/data/pg_hba.conf

# Expose PostgreSQL port
EXPOSE 5432
